version: "3.3"
services:
  spark-master:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  spark-worker-b:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
#  demo-database:
#    image: postgres:11.7-alpine
#    ports: 
#      - "5432:5432"
#    environment: 
#      - POSTGRES_PASSWORD=casa1234
  
  jupyterlab:
    build:
      context: jupyter_docker
      dockerfile: ./Dockerfile
    container_name: jupyter-pyspark-notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - 8888:8888
      - 4040:4040
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    depends_on:
      - spark-master
    volumes:
      - ./data:/home/jovyan/work
  
  sambaserver:
    build:
      context: samba_docker
      dockerfile: ./Dockerfile
    container_name: samba-server-docker
    ports:
      - 135:135/tcp
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    volumes:
      - ./lan_share/:/shared

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=josh
      - POSTGRES_DB=jrp_test
  
  cloudbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8978:8978
    volumes:
      - ./cloudbeaver_data:/opt/cloudbeaver/workspace
